$(document).on('submit','#todo-form',function(e)
  {
    console.log('hello');
    e.preventDefault();
      $.ajax({
        type:'POST',
        url:'/',
        data:{
          start_date:$("#start_date").val()
        },
        success:function()
        {
          alert('saved');
        }
      })
    });
